---
- hosts: test

  become: yes

  tasks: 

    - name: deploy app

      shell: kubectl create deploy myapp --image=parankusam/phpsample:{{ build }}

    - name: increase replicas 

      shell: kubectl scale deploy myapp --replicas=2

    - name: deploy service

      shell: kubectl expose deploy myapp --name myapp-svc --port 8080 --type NodePort
